<?php

/**
 * @file 
 * Primarily Backdrop hooks for Image Grid Blocks module.
 */

/**
 * Implements hook_autoload_info().
 */
function image_grid_block_autoload_info() {
  return array(
    'ImageGridBlock' => 'image_grid_block.block.inc',
  );
}

/**
 * Implements hook_theme().
 */
function image_grid_block_theme() {
  return array(
    'image_grid_block_content' => array(
      'render element' => 'elements',
      'template' => 'image_grid_block-content',
    ),
  );  
}

/**
 * Implements hook_menu().
 */
function image_grid_block_menu() {
  $items['admin/structure/image_grid_block'] = array(
    'title' => 'Image Grid Blocks',
    'description' => 'List and configure Image Grid Blocks.',
    'page callback' => 'image_grid_block_list',
    'access arguments' => array('administer layouts'),
    'file' => 'image_grid_block.admin.inc',
  );
  $items['admin/structure/image_grid_block/list'] = array(
    'title' => 'IIV Blocks',
    'description' => 'List of existing Image Grid Blocks.',
    'page callback' => 'image_grid_block_list',
    'access arguments' => array('administer layouts'),
    'file' => 'image_grid_block.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/image_grid_block/image_grid_block_configure'] = array(
    'title' => 'Settings',
    'description' => 'Configure Image Grid Block settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('image_grid_block_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'image_grid_block.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/structure/image_grid_block/%/delete'] = array(
    'title' => 'Delete Image Grid Blocks',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('image_grid_block_block_delete', 3),
    'access arguments' => array(3),
    'access callback' => 'image_grid_block_delete_access',
    'type' => MENU_CALLBACK,
    'file' => 'image_grid_block.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_config_info().
 */
function image_grid_block_config_info() {
  $prefixes['image_grid_block.settings'] = array(
    'label' => t('Image Grid Block settings'),
    'group' => t('Configuration'),
  );
  // Note that image files are not exportable.
  $prefixes['image_grid_block.block'] = array(
    'name_key' => 'machine_name',
    'label_key' => 'label',
    'group' => t('Image Grid Blocks'),
  );
  return $prefixes;
}

/**
 * Implements hook_block_info().
 */
function image_grid_block_block_info() {
  $blocks = array();
  $default_info = t('A basic block for adding custom text and an image with effects.');
  $blocks['default'] = array(
    'info' => t('Image Grid Block'),
    'description' => $default_info,
    'class' => 'ImageGridBlock',
  );
  // Image Grid Blocks are reusable.
  $config_names = config_get_names_with_prefix('image_grid_block.block.');
  foreach ($config_names as $config_name) {
    $block = config_get($config_name);
    $block_info = array();
    $block_info['info'] = $block['label'];
    $block_info['class'] = 'ImageGridBlock';
    $block_info['description'] = $default_info;
    $blocks[$block['machine_name']] = $block_info;
  }
  return $blocks;
}

/**
 * Load a single Image Grid Block by its machine name.
 *
 * Helper function for #machine_name form item.
 */
function image_grid_block_load($name = '') {
  $block = config_get('image_grid_block.block.' . $name);
  if (!$block) {
    return FALSE;
  }
  return $block;
}

/**
 * Implements template_preprocess_block().
 */
function image_grid_block_preprocess_block(&$variables) {
  if ($variables['block']->module == 'image_grid_block') {
    $variables['classes'][] = 'image-grid-block';
    if ($variables['block']->delta == 'default') {
      $machine_name = $variables['block']->settings['machine_name'];
      $variables['classes'][] = backdrop_html_class('image-grid-block-' . $machine_name);
    }
  }
}



